#!/bin/bash

# =============================================================================
# Dash - Setup Automated Backup
# Configures cron job for daily backups with optional SSH transfer
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="${DASH_CONFIG_DIR:-/etc/dash}"
BACKUP_WRAPPER="$SCRIPT_DIR/backup-cron.sh"
LOG_FILE="/var/log/dash-backup.log"
# Exact comment appended to our crontab line; used to find/remove only that line.
CRON_MARKER="# dash automated backup"

# Resolve the data directory the same way the server and backup.sh do:
# environment, then server/.env, then <project>/data.
DATA_DIR="${DASH_DATA_DIR:-}"
if [ -z "$DATA_DIR" ] && [ -f "$PROJECT_DIR/server/.env" ]; then
    DATA_DIR=$(grep -m1 "^DASH_DATA_DIR=" "$PROJECT_DIR/server/.env" | cut -d= -f2- | tr -d '"'"'")
fi
DATA_DIR="${DATA_DIR:-$PROJECT_DIR/data}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --daily              Enable daily backups at 2 AM"
    echo "  --hourly             Enable hourly backups"
    echo "  --ssh USER@HOST:PATH Enable SSH transfer to remote server"
    echo "  --keep N             Keep last N backups (default: 30)"
    echo "  --disable            Disable automated backups"
    echo "  --status             Show current backup configuration"
    echo ""
    echo "Examples:"
    echo "  $0 --daily"
    echo "  $0 --daily --ssh user@backup-server:/backups/dash"
    echo "  $0 --daily --ssh user@server:/backups --keep 14"
    echo "  $0 --disable"
    exit 0
}

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    SUDO=""
else
    SUDO="sudo"
fi

# Parse arguments
SCHEDULE=""
SSH_TARGET=""
KEEP_BACKUPS=30
ACTION=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --daily)
            SCHEDULE="daily"
            shift
            ;;
        --hourly)
            SCHEDULE="hourly"
            shift
            ;;
        --ssh)
            SSH_TARGET="$2"
            shift 2
            ;;
        --keep)
            KEEP_BACKUPS="$2"
            shift 2
            ;;
        --disable)
            ACTION="disable"
            shift
            ;;
        --status)
            ACTION="status"
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Handle status check
if [ "$ACTION" = "status" ]; then
    echo ""
    echo -e "${BLUE}Dash Backup Configuration${NC}"
    echo "========================="

    if [ -f "$CONFIG_DIR/backup.conf" ]; then
        cat "$CONFIG_DIR/backup.conf"
    else
        echo "No backup configuration found."
    fi

    echo ""
    echo "Cron jobs:"
    crontab -l 2>/dev/null | grep -F -e "$CRON_MARKER" -e "$BACKUP_WRAPPER" || echo "No backup cron jobs found."
    echo ""
    exit 0
fi

# Handle disable
if [ "$ACTION" = "disable" ]; then
    log_info "Disabling automated backups..."

    # Remove only our own cron line (exact marker comment or exact wrapper path),
    # never other jobs that happen to mention "dash" or "backup".
    crontab -l 2>/dev/null | grep -v -F -e "$CRON_MARKER" -e "$BACKUP_WRAPPER" | crontab - 2>/dev/null || true

    # Remove config
    $SUDO rm -f "$CONFIG_DIR/backup.conf" 2>/dev/null || true

    log_success "Automated backups disabled"
    exit 0
fi

# Require schedule for setup
if [ -z "$SCHEDULE" ]; then
    log_error "Please specify --daily or --hourly"
    usage
fi

echo ""
echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}  Dash - Setup Automated Backup${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

# Create config directory
$SUDO mkdir -p "$CONFIG_DIR"

# Create backup configuration
log_info "Creating backup configuration..."

$SUDO tee "$CONFIG_DIR/backup.conf" > /dev/null << EOF
# Dash Backup Configuration
# Generated: $(date)

DASH_PROJECT_DIR=$PROJECT_DIR
DASH_DATA_DIR=$DATA_DIR
DASH_KEEP_BACKUPS=$KEEP_BACKUPS
DASH_SSH_TARGET=$SSH_TARGET
DASH_SCHEDULE=$SCHEDULE
EOF

log_success "Configuration saved to $CONFIG_DIR/backup.conf"
log_info "Backing up database from: $DATA_DIR/dash.db"

# Create the backup wrapper script
cat > "$BACKUP_WRAPPER" << 'WRAPPER'
#!/bin/bash
# Dash automated backup wrapper (generated by scripts/setup-backup.sh)

# Load configuration. `set -a` exports every variable the file defines so that
# DASH_DATA_DIR / DASH_KEEP_BACKUPS actually reach backup.sh (a child process).
CONFIG_FILE="${DASH_CONFIG_DIR:-/etc/dash}/backup.conf"
if [ -f "$CONFIG_FILE" ]; then
    set -a
    source "$CONFIG_FILE"
    set +a
fi

PROJECT_DIR="${DASH_PROJECT_DIR:-$(dirname "$(dirname "$0")")}"
BACKUP_SCRIPT="$PROJECT_DIR/scripts/backup.sh"
LOG_FILE="/var/log/dash-backup.log"

# Run backup. backup.sh prints the archive path as its last stdout line and
# exits non-zero on failure (e.g. no database found).
echo "[$(date)] Starting backup..." >> "$LOG_FILE" 2>&1
BACKUP_OUTPUT=$("$BACKUP_SCRIPT" 2>> "$LOG_FILE")
BACKUP_STATUS=$?
BACKUP_FILE=$(printf '%s\n' "$BACKUP_OUTPUT" | tail -n1)

if [ "$BACKUP_STATUS" -eq 0 ] && [ -n "$BACKUP_FILE" ] && [ -f "$BACKUP_FILE" ]; then
    echo "[$(date)] Backup created: $BACKUP_FILE" >> "$LOG_FILE"

    # SSH transfer if configured
    if [ -n "$DASH_SSH_TARGET" ]; then
        echo "[$(date)] Transferring to $DASH_SSH_TARGET..." >> "$LOG_FILE"
        scp "$BACKUP_FILE" "$DASH_SSH_TARGET/" >> "$LOG_FILE" 2>&1

        if [ $? -eq 0 ]; then
            echo "[$(date)] Transfer complete" >> "$LOG_FILE"
        else
            echo "[$(date)] ERROR: Transfer failed" >> "$LOG_FILE"
        fi
    fi

    echo "[$(date)] Backup complete" >> "$LOG_FILE"
else
    echo "[$(date)] ERROR: Backup failed (exit $BACKUP_STATUS)" >> "$LOG_FILE"
    printf '%s\n' "$BACKUP_OUTPUT" >> "$LOG_FILE"
    exit 1
fi
WRAPPER

chmod +x "$BACKUP_WRAPPER"
log_success "Backup wrapper script created"

# Setup cron job
log_info "Setting up cron job..."

# Remove our existing cron line (matched by exact marker comment or exact
# wrapper path only, so unrelated jobs are never dropped)
CURRENT_CRON=$(crontab -l 2>/dev/null | grep -v -F -e "$CRON_MARKER" -e "$BACKUP_WRAPPER" || true)

# Add new cron job
case $SCHEDULE in
    daily)
        CRON_SCHEDULE="0 2 * * *"  # 2 AM daily
        ;;
    hourly)
        CRON_SCHEDULE="0 * * * *"  # Every hour
        ;;
esac

NEW_CRON="$CURRENT_CRON
$CRON_SCHEDULE $BACKUP_WRAPPER  $CRON_MARKER"

echo "$NEW_CRON" | crontab -

log_success "Cron job configured ($SCHEDULE at ${CRON_SCHEDULE})"

# Test SSH connection if configured
if [ -n "$SSH_TARGET" ]; then
    log_info "Testing SSH connection to $SSH_TARGET..."

    # Extract host from target
    SSH_HOST=$(echo "$SSH_TARGET" | cut -d: -f1)

    if ssh -o BatchMode=yes -o ConnectTimeout=5 "$SSH_HOST" "echo ok" &>/dev/null; then
        log_success "SSH connection successful"
    else
        log_warn "SSH connection failed. Please ensure:"
        log_warn "  1. SSH key is set up (ssh-copy-id $SSH_HOST)"
        log_warn "  2. Target directory exists"
        log_warn "Backups will still be created locally."
    fi
fi

# Create log file. The cron job runs from the invoking user's crontab, so that
# user must be able to write it; give it to them (644) instead of making it
# world-writable.
CRON_USER="${SUDO_USER:-$USER}"
$SUDO touch "$LOG_FILE"
$SUDO chown "$CRON_USER" "$LOG_FILE"
$SUDO chmod 644 "$LOG_FILE"

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Automated Backup Configured!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo -e "  ${BLUE}Schedule:${NC} $SCHEDULE ($CRON_SCHEDULE)"
echo -e "  ${BLUE}Data directory:${NC} $DATA_DIR"
echo -e "  ${BLUE}Keep backups:${NC} $KEEP_BACKUPS"
if [ -n "$SSH_TARGET" ]; then
echo -e "  ${BLUE}SSH target:${NC} $SSH_TARGET"
fi
echo -e "  ${BLUE}Log file:${NC} $LOG_FILE"
echo ""
echo -e "  ${YELLOW}Commands:${NC}"
echo -e "    View logs: tail -f $LOG_FILE"
echo -e "    Run now:   $BACKUP_WRAPPER"
echo -e "    Status:    $0 --status"
echo -e "    Disable:   $0 --disable"
echo ""
